config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get 'users/index'
  get 'users/update'
  get 'users/edit'
  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def update
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Soi
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/index.html.haml
hello haml!

app/views/users/index.html.haml
.body
.grad
.header
  %div
    Site
    %span Random
%br/
.login
  %input{name: "user", placeholder: "username", type: "text"}/
  %br/
  %input{name:  "password", placeholder:  "password", type:  "password"}/
  %br/
  -# %input{type:  "button", value:  ""}/
  = link_to users_edit_path do
    login

app/views/users/update.html.haml
.bottom-content
  %form.contact-form
    %h2.heading-name 注文者情報を記入して下さい
    name
    %input.small-field{:placeholder => "name", :type => "text"}/
    address
    %input.small-field{:placeholder => "e-mail", :type => "text"}/
    支払い方法
    %textarea.large-field{:placeholder => "message"}
    %input.send{:type => "submit", :value => "注文を確定"}/